# Generated by Django 3.2.7 on 2021-09-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_min', models.IntegerField(default=0)),
                ('value_max', models.IntegerField(default=0)),
                ('display_min', models.IntegerField(default=0)),
                ('display_max', models.IntegerField(default=0)),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='color_swatch.colorspace')),
            ],
        ),
    ]
